diff_drive_controller:
  type        : "diff_drive_controller/DiffDriveController"
  left_wheel  : 'wheel_left_joint'
  right_wheel : 'wheel_right_joint'
  publish_rate: 10     #odometry          # default: 50

  #6x6 matrix diagonal. Trust you have in your sensor for each Dof. You have 6 Dof, position (x, y, z) and orientation (x, y, z)
  pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  # Wheel separation and diameter. These are both optional.
  # diff_drive_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter
  wheel_separation : 0.536 #m
  wheel_radius : 0.095 #m

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  #wheel_radius_multiplier    : 1.3 # default: 1.0
  left_wheel_radius_multiplier: 1.0
  right_wheel_radius_multiplier: 1.0

  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 2

  # Base frame_id
  base_frame_id: base_link #default: base_link

  # Velocity and acceleration limitskm
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 0.3325 #0.341325  # m/s
      min_velocity           : -0.3325 #-0.341325 # m/s
      has_acceleration_limits: true
      max_acceleration       : 8 #1.73  # m/s^2
      min_acceleration       : -8 #-1.73 # m/s^2
      has_jerk_limits        : true
      max_jerk               : 20 #1.0  # m/s^3
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 1.0 #1.29  # rad/s
      has_acceleration_limits: true
      max_acceleration       : 8 #2.32  # rad/s^2
      has_jerk_limits        : true
      max_jerk               : 20 #2.5  # rad/s^3
