local_costmap:
  plugins:
    - {name: laser_layer_temp, type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"} #Laser layer working
    - {name: inflation_layer,  type: "costmap_2d::InflationLayer"}

  update_frequency: 2.0 #HIGH CPU usage with sensors
  publish_frequency: 50.0 #Reducir para aligerar CPU
  global_frame: "odom" #To inflate obstacles
  robot_base_frame: "base_link"
  static_map: true
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.1
