name: Continuous Integration

on:
  push:
    branches:
      - 'main'

env:
  IMAGE_NAME: lola2_noetic

jobs:
  docker-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout source code
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/gramuah/${{env.IMAGE_NAME}}
          tags: |
            latest
            type=sha
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}